name: Context And Expression
on: push

jobs:
  one:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: ${{join(github.event.repository.default_branch)}}
      MASTER_BRANCH: ${{join(github.event.repository.master_branch)}}
    steps:
      - name: Dump Branch Name
        run: echo "DEFAULT_BRANCH = $DEFAULT_BRANCH , MASTER_BRANCH = $MASTER_BRANCH"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Text
        env:
          myNull: ${{ null }}
          myBoolean: ${{ false }}
          myIntegerNumber: ${{ 711 }}
          myFloatNumber: ${{ -9.2 }}
          myHexNumber: ${{ 0xff }}
          myExponentialNumber: ${{ -2.99e2 }}
          myString: ${{ 'Mona the Octocat' }}
          myEscapedString: ${{ 'It''s open source!' }}
        run: echo "$myNull $myBoolean $myIntegerNumber $myFloatNumber $myHexNumber $myExponentialNumber $myString $myEscapedString"
