name: Build and Deploy Docs
on:
  push:
    branches:
      - main
      - v*
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install and Build
        run: |
          pnpm install
          pnpm run docs:build
      - name: Deploy
        if: ${{github.ref == 'refs/heads/main'}}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN_WORKFLOW }}
          publish_dir: docs-dist
          destination_dir: main
      - name: Deploy
        if: ${{github.ref != 'refs/heads/main'}}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN_WORKFLOW }}
          publish_dir: docs-dist
          destination_dir: ${{github.ref}}
