name: GitHub Actions Demo
# on: [push, pull_request]
on:
  push:
    branches:
      - main
jobs:
    runs-on: ubuntu-latest
  my_first_job:
    name: My first job
    steps:
      - run: echo "1"
      - run: echo "2"
  my_second_job:
    name: My second job
    needs: [my_first_job]
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
